### ISSUE TITLE
Taking Very Long Time and Unable to give output

### ISSUE THREAD

**Issue by shivam-maurya-git** [ibrahim-string/SiteScraper#1]
@ibrahim-string 
**This is the just shown in output and code is running still**
`DevTools listening on ws://127.0.0.1:62866/devtools/browser/5ca19b58-a8b9-443d-b64c-b877828ac9b2
[1128/012306.665:INFO:CONSOLE(5019)] "LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.", source: https://www.youtube.com/s/desktop/bd3558ba/jsbin/desktop_polymer_legacy_browsers.vflset/desktop_polymer_legacy_browsers.js (5019)`

![Screenshot 2023-11-28 012801](https://github.com/ibrahim-string/SiteScraper/assets/74864959/3113d89a-2de7-454e-b8a7-c0057c007695)
This is my code.

**Comment by ibrahim-string** [comment]
@shivam-maurya-git you are using the wrong url. 
The `yt_vedios_data` method will only work if you pass the right url. 
You should go to the videos sections of the youtube channel and then copy the url. 
Here is the right url : `https://www.youtube.com/@CarryMinati/videos`
The error you are citing is not an error. 
You have to wait untill the script scrolls to the bottom of the page.
